export const US_STATE_OPTIONS = [
  ["AL", "Alabama"],
  ["AK", "Alaska"],
  ["AZ", "Arizona"],
  ["AR", "Arkansas"],
  ["CA", "California"],
  ["CO", "Colorado"],
  ["CT", "Connecticut"],
  ["DE", "Delaware"],
  ["DC", "District of Columbia"],
  ["FL", "Florida"],
  ["GA", "Georgia"],
  ["HI", "Hawaii"],
  ["ID", "Idaho"],
  ["IL", "Illinois"],
  ["IN", "Indiana"],
  ["IA", "Iowa"],
  ["KS", "Kansas"],
  ["KY", "Kentucky"],
  ["LA", "Louisiana"],
  ["ME", "Maine"],
  ["MD", "Maryland"],
  ["MA", "Massachusetts"],
  ["MI", "Michigan"],
  ["MN", "Minnesota"],
  ["MS", "Mississippi"],
  ["MO", "Missouri"],
  ["MT", "Montana"],
  ["NE", "Nebraska"],
  ["NV", "Nevada"],
  ["NH", "New Hampshire"],
  ["NJ", "New Jersey"],
  ["NM", "New Mexico"],
  ["NY", "New York"],
  ["NC", "North Carolina"],
  ["ND", "North Dakota"],
  ["OH", "Ohio"],
  ["OK", "Oklahoma"],
  ["OR", "Oregon"],
  ["PA", "Pennsylvania"],
  ["RI", "Rhode Island"],
  ["SC", "South Carolina"],
  ["SD", "South Dakota"],
  ["TN", "Tennessee"],
  ["TX", "Texas"],
  ["UT", "Utah"],
  ["VT", "Vermont"],
  ["VA", "Virginia"],
  ["WA", "Washington"],
  ["WV", "West Virginia"],
  ["WI", "Wisconsin"],
  ["WY", "Wyoming"],
  ["AS", "American Samoa"],
  ["GU", "Guam"],
  ["MP", "Northern Mariana Islands"],
  ["PR", "Puerto Rico"],
  ["VI", "U.S. Virgin Islands"]
] as const;

export const PROFILE_LANE_OPTIONS = [
  ["Builder", "Builder — owns or builds the thing"],
  ["Operator", "Operator — turns plans into repeatable work"],
  ["Backer", "Backer — supplies capital or financial muscle"],
  ["Connector", "Connector — knows who or what is missing"],
  ["Spark", "Spark — brings the opening, idea, or unusual edge"]
] as const;

export const PROFILE_VISIBILITY_OPTIONS = [
  ["full_name", "Full name"],
  ["first_name_only", "First name only"],
  ["alias", "Display name or alias"]
] as const;

export const PRIMARY_GOAL_SUGGESTIONS = [
  "Generational Family Business",
  "Buy or take over a business",
  "Grow an existing business",
  "Find an operating partner",
  "Raise capital for a real project",
  "Put capital to work",
  "Move from employee to owner",
  "Launch a new venture",
  "Venture Scale/Exit",
  "Sell or transition a business"
] as const;
